# Generated by Django 4.0.2 on 2024-07-13 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0004_alter_member_membership'),
        ('controller', '0003_credit_enable_booster_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OthersCredit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_settings.month')),
            ],
        ),
    ]
