# Generated by Django 4.0.2 on 2024-07-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('monthly_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booster_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
